name: Deploy Integration Azure Function [stage]
on:
  workflow_dispatch:
  push:
    branches:
      - funct-test-local-ref-data 

env:
  AZURE_FUNCTIONAPP_NAME: "fn-invoker-application"
  NODE_VERSION: "14.17.3"
  AZURE_STORAGE_CONTAINER_NAME: "ksad-graph-raw-data-dev"
  AZURE_STORAGE_FOLDER_PATH: "pia/test_folder/merged_rdf_files"
  AZURE_STORAGE_CONTAINER_NAME_REFINED_DATA: "ksad-graph-raw-data-dev"
  AZURE_STORAGE_FOLDER_PATH_REFINED_DATA: "pia/test_folder/refined_files"
  KEY_VAULT_NAME: "kv-ksad-db-dev"
  GRAPHDB_HOST_IP: "10.32.1.14"
  GRAPHDB_HOST_PORT: "7200"


jobs:
  deploy-storage-graphdb-integration-function:
    name: Deploy Azure Storage Container & GraphDB Integration Function
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
        working-directory: storage-graphdb-integration-function
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
          node-version: ${{ env.NODE_VERSION }}

    - name: "Az CLI login"
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
